### ISSUE TITLE
Flatten HttpRequestState

### ISSUE THREAD

**Issue by PeterSR** [daiscog/ngx-http-request-state#10]
Hi!

Thank you for this framework!

I am facing a problem and wondered if there is a idiomatic way to handle it using this framework.
Suppose I perform n requests with `forkJoin` that I would like to combine when they all finish. 
It means somehow combining the `value` of each state into another value base on some kind of flattening logic (something something monad). 

Here's my own solution:

```typescript
import { ErrorState, HttpRequestState, isErrorState, isLoadedState, LoadedState, LoadingState } from "ngx-http-request-state"

export function flattenHttpRequestStates<T>(
  states: HttpRequestState<T>[],
  flattenValues: (states: LoadedState<T>["value"][]) => LoadedState<T>["value"],
  flattenErrors?: (states: ErrorState<T>["error"][]) => ErrorState<T>["error"],
): HttpRequestState<T> {
  if (states.every(isLoadedState)) {
    const state: LoadedState<T> = {
      isLoading: false,
      value: flattenValues(states.map(s => s.value)),
      error: undefined,
    }
    return state
  }

  if (states.some(isErrorState)) {
    if (flattenErrors === undefined) {
      flattenErrors = (errors: ErrorState<T>["error"][]) => errors[0]
    }

    const errorStates = states.filter(isErrorState)
    const state: ErrorState<T> = {
      isLoading: false,
      value: undefined,
      error: flattenErrors(errorStates.map(s => s.error)),
    }
    return state
  }

  const state: LoadingState<T> = {
    isLoading: true,
    value: undefined,
    error: undefined,
  }

  return state
}
```

(Note: To get loading updates I needed to also change `forkJoin` to `combineLatest` when I use this function)

Is there a better way to do it or would it make sense to build this function in to the framework?

**Comment by daiscog** [comment]
Hi,

When I've had similar requirements in the past, I've just used combineLatest for the requests, then wrapped that in the HttpRequestState.  Something like this:

```ts
import { loadingState, errorState, loadedState } from "ngx-http-request-state"

//...

combineLatest([
  httpClient.get(/* request 1 */),
  httpClient.get(/* request n */),
]).pipe(
  map((responses) => loadedState(responses)),
  startWith(loadingState()),
  catchError((err) => of(errorState(err)))
)
```

This should give you a loading state to start with, then either:

* a loaded state containing an array of all the individual responses
* an error state containing the first error that occurred

But I have also seen a flatten/merge approach used, similar to what you've suggested.

I'll keep this open and consider it for inclusion.

**Comment by daiscog** [comment]
Hey @PeterSR - yes, a PR would be welcomed.

(To be honest, I regret the naming of this lib, as I think it suggests that people should pipe their http requests at the low level through `httpRequestStates`. The intention was more for providing a _view model_ loading state where you'd prep all the data first, then pipe through `httpRequestStates` towards the end.)

**Comment by PeterSR** [comment]
I have made a proposal here: https://github.com/daiscog/ngx-http-request-state/pull/11
