### ISSUE TITLE
feat request: Keep previous value

### ISSUE THREAD

**Issue by klocus** [daiscog/ngx-http-request-state#22]
It would be nice to be able to keep the previous value, e.g. when moving to the next page of a table, without having to delete all the rows.

```
.pipe(httpRequestStates({ keepPreviousValue: true }));
```

**Comment by daiscog** [comment]
Thanks for the suggestion.  If I understand the use case, it is to keep the current page of data visible while loading the next page of data.  If so, then I think this does sound useful.

I think we could actually be a little more expressive in the options available:

```ts

interface StateTransitionOptions {
    /** Whether to retain the previous value when moving to a loading state.  Default is false */
    keepPreviousValueOnLoading?: boolean;
    /** Whether to retain the previous value when moving to an error state.  Default is false */
    keepPreviousValueOnError?: boolean;
    /**
     * A callback for merging the new and old values when moving to a loaded state.
     * Useful for infinite loading, etc., e.g. `onLoaded: (next, prev) => [...prev, ...next]`
     * Default if not set is `(next) => next`
     *
    onLoaded?: (next: T, prev?: T) => T;
}
```

**Comment by klocus** [comment]
> If I understand the use case, it is to keep the current page of data visible while loading the next page of data.

That’s correct!

**Comment by daiscog** [comment]
Hi @klocus 

Sorry for the delay with this.  Having given it some thought and started on an implementation, I'm now not convinced adding this option to the `httpRequestStates` function is useful.

The typical way of allowing a "load more" pattern would be something like this:

```ts
// assuming some loadMore$ source observable that emits the next 'from' cursor:

data$ = this.loadMore$.pipe(
  switchMap(
   (from) => this.http.get(`/api/get-data?from=${from}`).pipe(httpRequestStates()) 
  )
)
```

Note that here we're using `httpRequestStates` **inside** the `switchMap` callback, not after it.  So it's a new call to `httpRequestStates` every time the source observable emits, and there's no way of knowing at this point what has been emitted by previous requests.

For any `keepPreviousValue` implementation to work, we'd need to move the `httpRequestStates()` operator out of the inner observable and place it _after_ the `switchMap`.  But this means any errors thrown by the inner observable will cause the swtichMap to unsubscribe from the source observable, so we'd have no way of continuing to respond to further `loadMore$` events after an error is emitted by the http request (e.g., a flaky network caused the user's connection to drop momentarily).

For non-trivial scenarios like a "load more" pattern, we can use existing RxJS operators to merge the values that are emitted.  Two options are either a `scan` or a `startWith` and `pairwise` combination.  E.g., using `scan`:

```ts
//// With some utils:

/** The data that we're loading over time */
type LoadMoreList<T> = {
  moreAvailable: boolean;
  items: T[];
}

/** A function to merge the next page on top of the data loaded so far */
function mergeValues<T>(prev: LoadMoreList<T>, next: LoadMoreList<T>) {
  return {
    moreAvailable: next.moreAvailable,
    items: [
      ...prev.items,
      ...next.items,
    ]
  }
}

/** An initial, empty value */
const INITIAL_STATE = loadedStatus<LoadMoreList<any>>({moreAvailable: true, items: []})


//// Then in our component:

data$ = this.loadMore$.pipe(
  switchMap(
   (from) => this.http.get(`/api/get-data?from=${from}`).pipe(httpRequestStates()) 
  ),
  scan((prev, next) => ({
    ...next,
    // For loaded states merge the values, for other states inherit the previous value:
    value: next.value ? mergeValues(prev, next) : prev.value 
  }), INITIAL_STATE)
)
```

This library could provide a util operator that encapsulates the function of this scan, but it seems rather trivial (the existing `scan` operator requires a very small amount of code) so I'm not sure it would offer much value.
